### ISSUE TITLE
Is a particular Java JDK version necessary?

### ISSUE THREAD

**Issue by moulayghaitaoui** [Chargily/chargily-epay-java#12]
porject {https://github.com/moulayghaitaoui/Import_chargily_epay_java_Android.git }
![image](https://github.com/Chargily/chargily-epay-java/assets/64228972/532447d2-89c9-4cb8-8adc-e7eeba33aafe)

**Comment by mrsofiane** [comment]
Hello @moulayghaitaoui, java 17 is required to use the v1.1 and java 16 to use the v1.0

**Comment by moulayghaitaoui** [comment]
Hello @mrsofiane  I use java 17 version "17.0.8" 2023-07-18 LTS
is required to use the v1.1  But I'm having difficulty In reaching class invoice
![image](https://github.com/Chargily/chargily-epay-java/assets/64228972/a7fb6263-748b-443f-8c3a-d5dca5544ddd)

**Comment by mrsofiane** [comment]
Hello @moulayghaitaoui , thanks for report, i see it's another dependency, you can add `implementation 'com.github.mvallim:java-fluent-validator:1.10.0'`
____
Going to open a PR to fix this library dependency.

**Comment by moulayghaitaoui** [comment]
Hello @mrsofiane When adding the library `'implementation 'com.github.mvallim:java-fluent-validator:1.10.0'` A conflict occurs with duplicate classes in project dependencies. 
![image](https://github.com/Chargily/chargily-epay-java/assets/64228972/36925231-3a00-4adb-88aa-aecef976a516)

**Comment by aziz011133** [comment]
@moulayghaitaoui  Did you find a solution? I also have the same issue.

**Comment by aziz011133** [comment]
@moulayghaitaoui  
![Annotation 2023-09-09 154813](https://github.com/Chargily/chargily-epay-java/assets/100021067/8fbfe7c0-fdc3-4898-a098-43df94d444e7)

> error duplicat class

**Comment by moulayghaitaoui** [comment]
Hello @aziz011133 No, I did not know the solution

**Comment by mrsofiane** [comment]
Hello @moulayghaitaoui @aziz011133 , you are having a class duplication error, you can exclude it to remove the conflicts.
can you provide a simple app to check the error.

**Comment by aziz011133** [comment]
@mrsofiane  Yes, when you implement the library, an error may appear indicating class duplication without using it
The problem is with the library itself
and a simple app to check the error. 
project [https://github.com/aziz011133/testpay](url)

**Comment by mrsofiane** [comment]
Hello @aziz011133, i see your having duplicates with org.aspecjt , you can exclude it with 

`implementation ('com.github.chargily:chargily-epay-java:1.1.1') {
        exclude group: "org.aspectj"
    }`

**Comment by moulayghaitaoui** [comment]
Hello @mrsofiane  The problem is still even after the library is included `implementation ('com.github.chargily:chargily-epay-java:1.1.1') { exclude group: "org.aspectj" }` 
project : https://github.com/moulayghaitaoui/Import_chargily_epay_java_Android.git
error 
![image](https://github.com/Chargily/chargily-epay-java/assets/64228972/42bc88c1-c5c4-4d82-a624-90031f55a3c9)

**Comment by mrsofiane** [comment]
Remove `implementation 'com.github.mvallim:java-fluent-validator:1.10.0` you dont need it in v1.1.1

**Comment by moulayghaitaoui** [comment]
Still the problem even after deleting the library `implementation 'com.github.mvallim:java-fluent-validator:1.10.0`

**Comment by moulayghaitaoui** [comment]
Still the problem even after deleting the library `implementation 'com.github.mvallim:java-fluent-validator:1.10.0`

**Comment by mrsofiane** [comment]
Hello @moulayghaitaoui , i cant help you more unless you provide more informations, try to use ` gradle dependencies` to see where the org.aspectj is used. i see that you import retrofit, in v1.1.1 you can remove it it will be imported automatically.

**Comment by mrsofiane** [comment]
@moulayghaitaoui open another issue, make sure you provide more information not just a screenshot.
