### ISSUE TITLE
How to get webhook_url  and back_url

### ISSUE THREAD

**Issue by moulayghaitaoui** [Chargily/chargily-epay-java#15]
![image](https://github.com/Chargily/chargily-epay-java/assets/64228972/6c26d420-14ae-4dcb-9674-9da7bdf8f494)

project :
https://github.com/moulayghaitaoui/Import_chargily_epay_java_Android.git

**Comment by mrsofiane** [comment]
From the [doc](https://dev.chargily.com/docs/pay-api) :

back_url | This url you will be redirected to after the payment is done, and must be active URL | required ; string ; url
-- | -- | --
webhook_url | This is the source url wich you will get information of payment responce | required ; string ; url

you should learn more about how webhooks works.

**Comment by moulayghaitaoui** [comment]
can you give me  an example back Url and webhook ?
Do not think the problem of back url 
![image](https://github.com/Chargily/chargily-epay-java/assets/64228972/c5e9d3d3-f440-49a4-9517-04f8da31f1c9)

**Comment by mrsofiane** [comment]
When you sumbit invoice to the API, the checkout endpoint will generate a checkout url, you will send this to the user interface, the user will checkout with card, the result will be send to your webhook api, and the user will will be redirected to the back_url ( url of your app for example).

![mermaid-diagram-2023-09-17-154258](https://github.com/Chargily/chargily-epay-java/assets/16692912/bedc37fb-d844-48fc-9ad3-f022659c38c3)

**Comment by moulayghaitaoui** [comment]
Hello @mrsofiane Thank you for the explanation, but how can I create URL webhook for activity main?

**Comment by mrsofiane** [comment]
Webhook url is and API ENDPOINT, you can't create api endpoint in android app, you need to create a backend server to handle the response from chargily api, you can use firebase to create  rest api endpoint quickly otherwise you can create your own backend, i suggest you learn more about rest api and what is a webhook.
