### ISSUE TITLE
I have a problem with including the library

### ISSUE THREAD

**Issue by moulayghaitaoui** [Chargily/chargily-epay-java#9]
![image](https://github.com/Chargily/chargily-epay-java/assets/64228972/1a3e213f-b9ce-4a79-81a7-47c9d6b713b0)

**Comment by mrsofiane** [comment]
Hello @moulayghaitaoui, do you have `repositories {
    maven { url 'https://jitpack.io' }
}` in your buidle.gradle ?

**Comment by moulayghaitaoui** [comment]
Yes I have
![image](https://github.com/Chargily/chargily-epay-java/assets/64228972/4d28f4ee-0d0e-43b5-a305-2e6a76f03785)

**Comment by mrsofiane** [comment]
In the builde.gradle(Lawyer) add the jitpack url inside the allprojects : `allprojects {
    repositories {
        maven { url 'https://jitpack.io' }
    }
}`

**Comment by moulayghaitaoui** [comment]
![image](https://github.com/Chargily/chargily-epay-java/assets/64228972/76b8e2aa-cfab-4a57-8ae9-c0b5eaed62ab)

**Comment by mrsofiane** [comment]
@moulayghaitaoui to solve this problem you should add retrofit2 library dependency  `com.squareup.retrofit2:retrofit:2.9.0` then import retrofit2.Response
___
The V1.1 will improve and fix this design issue.

**Comment by moulayghaitaoui** [comment]
![image](https://github.com/Chargily/chargily-epay-java/assets/64228972/96608c80-9959-4022-8646-4fd8c75dc96a)
Could you initiate a fresh project and incorporate the library?

**Comment by mrsofiane** [comment]
Does the above solve your issue ? Why you want a new project ? if there are updates it will be in newer versions, otherwise you can fork the project and update the library as you want (ask @ChargilyDev about the licence ).

**Comment by moulayghaitaoui** [comment]
He still didn't recognize me using the API key.

**Comment by moulayghaitaoui** [comment]
He still didn't recognize me using the API key.

**Comment by ChargilyDev** [comment]
Pull request from @mrsofiane ,
Problem sloved
